change build script to produce micheline
boltlabs-inc/tezos-contract pull request #57
Opened 2021-09-21 19:46 UTC by DariusParvin

- edit the build script to return the micheline version of the contract rather than the michelson version.
- Update pytezos test to read in micheline contract

2021-09-21 22:13 UTC, jakinyele requested changes
Expected to see an additional output for the micheline JSON. Otherwise, looks good.

2021-09-22 00:37 UTC, DariusParvin commented on build-contract.sh
> -cp ${TEMP_DIR}/compiled_contract/*_contract.tz ${CONTRACT_TARGET_DIR}/zkchannel_contract_${COMMIT_HASH}.tz && rm -rf $TEMP_DIR
yeah I agree. Added!

2021-09-22 18:25 UTC, yaymukund approved these changes
Approving this with one non-blocking improvement.

2021-09-22 19:03 UTC, jakinyele approved these changes
Agree with @yaymukund and updates look good to me.

2021-09-22 19:17 UTC, jakinyele commented
@DariusParvin looks like you'll need to resolve the conflicts w/ sample json files before merging

2021-09-22 19:43 UTC, DariusParvin commented
rebased and resolved conflict

2021-09-22 19:43 UTC, merged